### ISSUE TITLE
Fails to compile on CentOS 7 with GCC 4.8.5

### ISSUE THREAD

**Issue by yantarou** [cmosek/dns-flood#3]
On CentOS  7, `gcc` fails with the following error:

```
$ make
gcc -o dnsflood -g -DDEBUG dnsflood.c
dnsflood.c: In function ‘gen_random’:
dnsflood.c:230:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < len; ++i) {
     ^
dnsflood.c:230:5: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [dnsflood] Error 1
```

```
$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
```

```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```
